apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-credentials
data:
  credentials: |
    [default]
    aws_access_key_id = AKIA2AL7MHT3L7ZO5MGX
    aws_secret_access_key = 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