apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [default]
    aws_access_key_id = ASIA2AL7MHT3KSEYM473
    aws_secret_access_key = NTEzdF/dEKl16rwiILfAnRzd92r77eAqZDywrOWp
    aws_session_token = FwoGZXIvYXdzEA0aDBq1njME3Z/dEKBBziK8ATSUINT9Zhd4j5kYYNSzPANl5yKJaT5vjQ3/ib2H8h0lZ/q7OJ+/8Ox+UuMGjKIdpIhW6jsiCcKMZ0Z+r9qwVkMVmuHdeaiE/9uJevm0f9m3SHw/oaJSdHkAi1MHD5IQc7W30HX9LlB9epdf9ZdnVunpm1psBXHOu8HhtSxVJu3SU4XOH9zazCcqL1eMfzPTtYDA8n4evE/mWXvUNIdwKw4DKQmiA6QiaPfY371REMdN5XftUIFAe1kzLar+KPfRz5sGMi1ISnUEu5YBVTVIfVR6EVfCVNg014fE0XIF4PZv6s11Xro/aiW0jOHG4cBe6Ds=