name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag reverseproxy aryola4/reverseproxy
    - run: docker tag udagram-api-user aryola4/udagram-api-user
    - run: docker tag udagram-api-feed aryola4/udagram-api-feed
    - run: docker tag udagram-frontend:local aryola4/udagram-frontend
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push aryola4/reverseproxy
    - run: docker push aryola4/udagram-api-user
    - run: docker push aryola4/udagram-api-feed
    - run: docker push aryola4/udagram-frontend
